export const skills = [
  { name: "Html", link: "./Images/svg/html.svg" },
  { name: "css", link: "./Images/svg/css.svg" },
  { name: "javascript", link: "./Images/svg/javascript.svg" },
  { name: "react", link: "./Images/svg/react.svg" },
  { name: "next", link: "./Images/svg/nextjs.svg" },
  { name: "redux", link: "./Images/svg/redux.svg" },
  { name: "tailwind", link: "./Images/svg/tailwindcss.svg" },
  { name: "node js", link: "./Images/svg/nodejs.svg" },
  { name: "express js", link: "./Images/svg/express.svg" },
  { name: "python", link: "./Images/svg/python.svg" },
  { name: "mongodb", link: "./Images/svg/mongodb.svg" },
  { name: "my sql", link: "./Images/svg/mysql.svg" },
  { name: "git", link: "./Images/svg/git.svg" },
  { name: "docker", link: "./Images/svg/docker.svg" },
  { name: "graphql", link: "./Images/svg/graphql.svg" },
  { name: "elastic", link: "./Images/svg/elasticsearch.svg" },
  { name: "cypress", link: "./Images/svg/cypress.svg" },
  { name: "redis", link: "./Images/svg/redis.svg" },
];

export const projects = [
  {
    name: "Fintrack",
    gitLink: "https://github.com/trilochan-behera-dev/FinTrack",
    webLink: "https://fintracks.vercel.app/",
    tags: ["Finance", "Savings", "Expense"],
    title: "Finance Tracking platform",
    image: "./Images/project/fintrack.png",
    projectFor: "Personal",
    desc: "Empower your financial journey with our intuitive finance tracking website. Seamlessly manage expenses, track income, and gain valuable insights into your financial health for a more secure and informed future.",
  },
  {
    name: "Portfolio",
    gitLink: "https://github.com/trilochan-behera-dev/Portfolio",
    webLink: "https://trilochan-behera.vercel.app/",
    tags: ["Personal", "Portfolio"],
    title: "Personal Portfolio",
    image: "./Images/project/portfolio.png",
    projectFor: "Personal",
    desc: "Welcome to my personal portfolio website, where creativity meets functionality. Explore my diverse projects, delve into my skills and experiences, and discover how I bring innovation and passion to every endeavor.",
  },
  {
    name: "TimeWise",
    gitLink: "https://github.com/trilochan-behera-dev/Time-Wise",
    webLink: "https://timewise.vercel.app/",
    tags: ["Google", "Calendar", "Events"],
    title: "Simple Calendar",
    image: "./Images/project/calendar.jpg",
    projectFor: "Personal",
    desc: "This project aims to create a calendar design like google and user can create, update and delete event.",
  },
  // {
  //     name: "Online Invoice App",
  //     gitLink: "https://github.com/trilochan-behera-dev/invoice_app",
  //     webLink: "https://simple-invoice-app.vercel.app/",
  //     tags: ["Invoice", "Tax", "Profit"],
  //     title: "Simple invoice app",
  //     image: "./Images/project/invoice.png",
  //     projectFor: "Personal",
  //     desc: "This project aims to create a simple invoice data, show the calculate data and update or delete the data."
  // },
  {
    name: "Book Slot Now",
    gitLink: "https://github.com/trilochan-behera-dev/BookYourSlot",
    webLink: "",
    tags: ["Covid", "Healthcare"],
    title: "Healthcare",
    image: "./Images/project/vaccine.jpg",
    projectFor: "Personal",
    desc: "The project aims to develop a slot booking portal. The portal will streamline the process of scheduling appointments, eliminating the need for manual coordination and allowing users to book slots at their convenience.",
  },
  {
    name: "E-learning",
    gitLink: "https://github.com/trilochan-behera-dev/E-Learning",
    webLink: "",
    tags: ["Online-course", "Leaning"],
    title: "Online learning",
    image: "./Images/project/elearning.jpg",
    projectFor: "Personal",
    desc: "This project aims to develop an eLearning course provider portal, a comprehensive online platform that offers a variety of courses to learners. The portal will provide a user-friendly interface for learners to browse, enroll in, and access courses.",
  },
  {
    name: "Alumni Feedback System",
    gitLink: "https://github.com/trilochan-behera-dev/Alumni_feeback_system",
    webLink: "",
    tags: ["Alumni", "Feedback"],
    title: "Institute",
    image: "./Images/project/alumni.jpg",
    projectFor: "Personal",
    desc: "This project aims to gather feedback from alumni to gain insights into their experiences and collect suggestions. By reaching out to past graduates, the project seeks to understand their perspectives, identify areas of strength and weakness, and implement changes for continuous improvement.",
  },
];
